language: python
python:
  - '3.6'
install:
  - make -C python requirements requirements-dev
  - make -C solidity npm-install
script:
  - make -C python
  - make -C solidity
  - make end-to-end
after_success:
  - cd python; make coverage-combine coverage-report; coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1f272f1a71c54afe08e7
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
